### ISSUE TITLE
[Feature request]: Offline‑capable self‑hosted MaterialDesignIcons & Roboto fonts

### ISSUE THREAD

**Issue by Manaa0-0** [defendicon/POS-Awesome-V15#354]
**Feature Request Description**
When the app is used without Internet connectivity, icons and Roboto text currently vanish because they’re pulled directly from CDNs. It would be great if the project provided a first‑class, out‑of‑the‑box way to bundle and cache these assets, so that:

* **Icons** (MaterialDesignIcons) and **Roboto** fonts continue to render when offline
* Preload tags are correctly configured (`as="font"` + `crossorigin`)
* A minimal Service Worker setup is included (optional) to cache all core CSS/JS/fonts on first load

from 
1. https://cdn.jsdelivr.net/npm/@mdi/font@6.x/css/materialdesignicons.min.css
2. https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900
---

**Use Case / Motivation**

1. **Point‑of‑Sale terminals** and other kiosks often run in environments with intermittent or no Internet.
2. Relying on external CDNs causes missing glyphs/text when connection drops.
3. Manual self‑hosting is possible but error‑prone and not documented centrally.

---

**Proposed Solution**

* Add `/assets/fonts/mdi/` and `/assets/fonts/roboto/` directories containing the relevant `.woff2` and `.css` files
* Update HTML templates to reference the local files, with correct `<link rel="preload" as="font" crossorigin>`
* Provide an **optional** `sw.js` + registration snippet that pre‑caches these assets

```js
// sw.js
const CACHE_NAME = 'static-v1';
const ASSETS = [
  '/assets/fonts/mdi/materialdesignicons.min.css',
  '/assets/fonts/mdi/materialdesignicons-webfont.woff2',
  '/assets/fonts/roboto/roboto.css',
  '/assets/fonts/roboto/Roboto-Light.woff2',
  // …add other core files
];

self.addEventListener('install', e =>
  e.waitUntil(caches.open(CACHE_NAME).then(c => c.addAll(ASSETS)))
);

self.addEventListener('fetch', e =>
  e.respondWith(caches.match(e.request).then(r => r || fetch(e.request)))
);
```

---

**Acceptance Criteria**

* [ ] All icon/font CDN references replaced with local paths in the default template
* [ ] Preload tags present and valid in `<head>`

**Comment by Manaa0-0** [comment]
@defendicon @engahmed1190 could you please review this

**Comment by engahmed1190** [comment]
I will test it, but the problem is that it might overload memory

**Comment by Manaa0-0** [comment]
@engahmed1190 how about this to solve memory issue:
You can eliminate the need for any “offline” caching of fonts/icons altogether by bundling them directly into your app’s shipped files. That way, the browser just loads them from your web server (or local filesystem in an embedded kiosk) at startup—no Service Worker or Cache API required

**Comment by Manaa0-0** [comment]
@engahmed1190

## 1. Copy the font files and CSS into your project

1. **Download** the `.woff2` (and/or `.woff`) files and the accompanying CSS (e.g. `materialdesignicons.min.css`, your `roboto.css`) into your project’s **public** (or **static**) folder.

   ```
   /public
     /fonts
       /mdi
         ├─ materialdesignicons-webfont.woff2
         ├─ materialdesignicons-webfont.ttf
         └─ materialdesignicons.min.css
       /roboto
         ├─ Roboto-Light.woff2
         ├─ Roboto-Regular.woff2
         ├─ Roboto-Medium.woff2
         └─ roboto.css
   ```

2. **Edit the CSS** so that the `@font-face` URLs point to those local paths.

   ```css
   /* in /public/fonts/mdi/materialdesignicons.min.css */
   @font-face {
     font-family: "Material Design Icons";
     src: url("/fonts/mdi/materialdesignicons-webfont.woff2") format("woff2"),
          url("/fonts/mdi/materialdesignicons-webfont.ttf")  format("truetype");
     /* … */
   }
   ```

   ```css
   /* in /public/fonts/roboto/roboto.css */
   @font-face {
     font-family: "Roboto";
     font-weight: 300;
     font-style: normal;
     src: url("/fonts/roboto/Roboto-Light.woff2") format("woff2");
   }
   /* repeat for 400,500… */
   ```

---

## 2. Reference them in your HTML (or your framework’s index template)

Replace the CDN `<link>` tags with paths to your local copies:

```html
<!-- instead of the jsdelivr URL: -->
<link
  rel="stylesheet"
  href="/fonts/mdi/materialdesignicons.min.css"
/>

<!-- instead of Google-hosted Roboto: -->
<link
  rel="stylesheet"
  href="/fonts/roboto/roboto.css"
/>
```

Now on **every** page load the browser will fetch these files from your server. They become first‑class static assets and don’t require any special “offline cache” step.

---

## 3. (Optional) Inline small icon subsets to shrink your bundle

If you still want to reduce network payload—but without an offline cache—you can:

* **Subset** your icon font to only the glyphs you use (via IcoMoon or Fontello), download the tiny `.woff2 + CSS`, and drop that into `/public` instead of the full MDI pack.
* **Base64‑embed** very small fonts directly in your main CSS:

  ```css
  @font-face {
    font-family: "MySubsetIcons";
    src: url("data:font/woff2;base64,AAEAAAALAIAAAwAwT1MvMg8S…") format("woff2");
  }
  ```

  This inlines the font in your CSS bundle so there’s literally nothing else to fetch.

---

### Why this avoids “offline memory” use

* **No Service Worker** → no Cache storage is ever used
* **No Cache‑API** → your app simply loads static files from disk or your web server
* **Bundled assets** → browsers drop them from memory when the page is closed; there’s no persistent quota consumption

With this setup, your icons and fonts are “local” by construction. Once they’re shipped in your build, there’s no extra caching layer, no quota concerns, and they’ll always be there whether or not the user has an Internet connection at runtime.
